### ISSUE TITLE
Server Side Queries

### ISSUE THREAD

**Issue by peterski74** [MoonStorm/trNgGrid#101]
Could someone please post a fully working server side query example? Or point me to a working example other than the one on the site, I'm really struggling to work out which JS relates in the demo/js/index.js and please not just a mock but actually calling via $http.

Would really appreciate any feedback!! 

Would love to use this grid as it looks the cleanest out of the ones I've looked ....

**Comment by amanprodigy** [comment]
@joebordes trNgGrid implementation in MarvelJs really helped. In that App you have a conclusion table in which you compared it with angular smart table. Do you have a demo on angular smart table too? If yes please show that as I am having some problem in implementing server side pagination with smart table. lorenzofox hasnt given the full demo of server side pagination filtering and sorting on the demo page. And to me, trNgGrid is really the second choice.

**Comment by joebordes** [comment]
Hi,

Glad it helped, that is what I shared it for :-)

As I explain on the conclusion page, I couldn't get smarttable to do what I needed (note that this is about 5 months old, so it may very well have changed). I haven't looked back since, just kept on going with trngrid.

The best I can suggest is that you look at the commits of the smart table testing which are towards the end of august, I think I got the server side working (although I don't really remember).

Let us know what you decide.
