### ISSUE TITLE
 Attribute display-name not working

### ISSUE THREAD

**Issue by i4got10** [MoonStorm/trNgGrid#116]
Checkout last commit from master branch and encounter this issue

    th(field-name="text" display-name="another")

prints "text" instead of "another"

**Comment by MoonStorm** [comment]
Works quite well here:
http://moonstorm.github.io/trNgGrid/release/index.html#/Columns

Could you please create a fiddle with your problem. Please fork this one: http://jsfiddle.net/MoonStorm/pkuca2f8/

**Comment by i4got10** [comment]
Cant reproduce with latest release

**Comment by i4got10** [comment]
Ok, reproduce it it jsfiddle 

http://jsfiddle.net/i4got10/pkuca2f8/209/

The thing that broke everything is 

    TrNgGrid.defaultColumnOptions = {};

**Comment by i4got10** [comment]
Also, another question. How to hide column title?

`display-name=""` will show original column field name

**Comment by MoonStorm** [comment]
Wow, so many edge cases here :laughing: I never thought about any of them. Are you trying to break it on purpose? :smiling_imp:

**Comment by i4got10** [comment]
Nope, sorry:relaxed:  Just did not found it in documentation. Typically, directive defaults comes from provider, not from global object, confuses a bit.

http://benclinkinbeard.com/posts/creating-configurable-angular-directives-with-providers/
https://github.com/angular-ui/ui-select/blob/master/src/common.js#L89

I can send PR if you found it suitable for youself

**Comment by MoonStorm** [comment]
Let's talk about them, one by one.

The problem with the empty ``display-name`` cannot be solved in the current version I'm sorry. The fix is actually trivial but the problem is the sorting glyph which then displays in the wrong position. It might work in the next major release, where the CSS will be simplified to the point where the grid won't require any additional styling. Your workaround for now is to either customize the grid header cell (inserting an empty DIV in there will do) or target it with CSS.

Sorry about your troubles with the default column options. Never thought someone would replace the entire object.

When I started working on the grid, these were initially constants inside the grid, then people started using them as defaults. I realized this was a quick win and I encouraged this approach when probably I shouldn't have, and this is where we are today.
The concept of a configuration provider has been discussed before, and it's currently listed as a limitation on the first page of the demo/docs site. You might want to check out all the limitations listed in there before you dive in.
The work for a configuration provider was completed for the next major release. That version will contain a lot of breaking changes in areas such as localization, configuration, templates so an imminent release in unlikely.

**Comment by i4got10** [comment]
Thank you for detailed answer, I get it now. It is a pity that in the current version there are such limitation s. I'll wait for the upcoming release. Hope it will be soon

**Comment by MoonStorm** [comment]
:laughing: Really, the lack of a configuration provider is a show stopper for you? :laughing: :laughing:

**Comment by i4got10** [comment]
Nope, i use it actually. Even despite the fact that there is no configuration provider :laughing:. Little bit customizing and ola

![2015-03-30 13-01-30](https://cloud.githubusercontent.com/assets/1151154/6892396/09e4395c-d6dd-11e4-9892-6cf7e8351151.png)

My favorite feature is that everything started to work without extra effort. For example, select as a column filter. Another example is a column name showed as a input placeholder.

**Comment by MoonStorm** [comment]
Just WOW!!! That thing looks so nice! I like how you put the global search in the top left. That's where it should be actually...

**Comment by i4got10** [comment]
There is no way of guessing how it "should be". The main goal is the possibility and ease of customization. Each project requires an individual approach i think
