### ISSUE TITLE
How to pass $http.get() data to the table?

### ISSUE THREAD

**Issue by BoVut** [MoonStorm/trNgGrid#151]
I've already post this question on StackOverflow, but thought posting here would be more direct.

How to link the data to the table using AngularJS or C# Razor ?

**Comment by tbrzica** [comment]
Hi,
I am using this table with angular and $http.get data without any problem. 
First define the table:
<div ng-controller="tableCtrl">
<table tr-ng-grid="" items="dataForTable" fields="['id','name']">
       <thead>
               <tr>
                       <th field-name="id" display-name="ID"></th>
                       <th field-name="name" display-name="Description"></th>
                <tr>
       </thead>
</table>
</div>


Then in the controller define $scope.dataForTable and pass it $http.get() data : 

app.controller('tableCtrl',function($http,$scope){
       $http.get('/your/api').then(function(result){
                $scope.dataForTable=result.data;
        });
});

Because $http returns a promise, once your api returns data table will automatically load.

**Comment by tbrzica** [comment]
Hi,
I am using this table with angular and $http.get data without any problem. 
First define the table:

```
<div ng-controller="tableCtrl>
	<table tr-ng-grid="" items="dataForTable" fields="['id','name']">
		<thead>
			<tr>
				<th field-name="id" display-name="ID"></th>
				<th field-name="name" display-name="Description"></th>
			</tr>
		</thead>
	</table>
</div>

```

Then in the controller define $scope.dataForTable and pass it $http.get() data :
```
app.controller('tableCtrl',function($http,$scope){
         $http.get('/your/api').then(function(result){
                   $scope.dataForTable=result.data;
          });
});
```

Because $http returns a promise, once your api returns data table will automatically load.

**Comment by BoVut** [comment]
Thank you for replying,

I finally got it!

The table works like magic with all the sorting and filtering features.

Best,
Bo
