### ISSUE TITLE
Keys not being parsed properly.

### ISSUE THREAD

**Issue by samy100** [MoonStorm/trNgGrid#161]
I have a server side query that retrieves objects which the key names are prefixed with @ or $, for example '@value', '$type', etc. Passing this array of objects to your table somehow doesnt render it at all. Removing the prefixes beforehand fixes the issue but this is troblesome in some cases. I can post an example at some point but I'm on my mobile. Pardon my brevity. I would appreciate your feedback on this, thanks!

**Comment by MoonStorm** [comment]
Yep, it appears so. Something is stripping them out...

**Comment by MoonStorm** [comment]
Fixed and pushed to the ``master`` branch. [Test created on the demo site](http://moonstorm.github.io/trNgGrid/release/#/TestSpecialSymbols).

**Comment by samy100** [comment]
Wow thanks for the fast turnaround! It works!

**Comment by MoonStorm** [comment]
Just so you know, looked at the test again, and it appears Angular ignores fields beginning with the dollar sign in many of its operations. So for example column filtering does not work because of this.

There is [a case on angular](https://github.com/angular/angular.js/issues/4581#issuecomment-86085130) which reports this issue but was closed as **"works as expected"** :laughing:
