### ISSUE TITLE
dynamic column/fields selection with server-side paging throws error

### ISSUE THREAD

**Issue by malde** [MoonStorm/trNgGrid#176]
Hey, I'm using the table with huge datasets (think more than 30 columns and up), therefore I have to preselect (or let the user change) fields that should be displayed. A minimal example on how it's done you'll find here: http://plnkr.co/ZPGfSB9OjFDu74OgPtpK however, I don't know how to simulate the server-side here.

Now, regarding the error: If a new column is (de)selected, almost everytime this error is thrown:

```
Error: [$compile:ctreq] Controller 'trNgGrid', required by directive 'trNgGridBodyCell', can't be found!
http://errors.angularjs.org/1.3.15/$compile/ctreq?p0=trNgGrid&p1=trNgGridBodyCell
    at REGEX_STRING_REGEXP (angular.js:63)
    at getControllers (angular.js:7583)
    at nodeLinkFn (angular.js:7751)
    at compositeLinkFn (angular.js:7117)
    at nodeLinkFn (angular.js:7763)
    at compositeLinkFn (angular.js:7117)
    at publicLinkFn (angular.js:6996)
    at $get.boundTranscludeFn (angular.js:7135)
    at controllersBoundTransclude (angular.js:7795)
    at ngRepeatAction (angular.js:24681)
```

This does not happen in the plunker I've linked and only seems to affect the server-side version of doing this.

On a side note, it does not seem to affect the functionality, more like a heads up.

**Comment by MoonStorm** [comment]
I really want to get to the bottom of this, as someone else reported this issue a while back. 

Here is the updated plunker that simulates server-side. I see no errors in the console.
http://plnkr.co/edit/Eej2BiJwuNsMX5Ursr8C?p=preview

**Comment by malde** [comment]
I can in fact reproduce the error with you example. Here's how:
- go to page 2
- deselect one of the checkboxes up top
- "use selected columns"

This does throw the mentioned error.

**Comment by MoonStorm** [comment]
Got it! Thanks.

**Comment by imtiaz-m4** [comment]
I am also getting this error. Is this issue fixed?

**Comment by granato** [comment]
s

**Comment by granato** [comment]
Got the same error when loading in an array of objects and letting the user select the columns he wants to see. Is there someone that has a solution for this problem ?

**Comment by MoonStorm** [comment]
I can reproduce the error with malde's instructions, however I could never pinpoint the cause. It doesn't seem to cause any problems, which makes this even more weirder. If anyone figured it out, I'd like to know as well.

**Comment by granato** [comment]
In my understanding it happens when checking one of the columns too fast before the framework and controller is initialised.

It only happens in my application when I have a lot of records in my trNgGrid and I'm adding/removing columns dynamically before the previous rerender is done (because having +50 records takes a second or so). 

I think that making sure the controller is initialised before executing/rerendering would actually fix the issue.

**Comment by granato** [comment]
I fiddled a bit with the framework 
I changed 

    ]).directive(cellBodyDirective, [
        function () {
            return {
                restrict: 'A',

to 

    ]).directive(cellBodyDirective, [
        function () {
            return {
                restrict: 'E',


And now I did not have it again. Tried to reproduce it but i'm unable to do so.
Does that work with you guys ?

**Comment by MoonStorm** [comment]
Hmmm, what? the cell body directive is set via an attribute, not an element.

**Comment by robrotheram** [comment]
I can confirm @granato fix does work had the same issue when using  Angular Multiselect to dynamically show/hide various columns.

**Comment by MoonStorm** [comment]
All that does is to disable the directive, I don't consider it a fix.

**Comment by jimmony** [comment]
This caused us a problem recently because we had different versions installed 3.1.2 and 3.1.4. We noticed it because on every time we added a new column the page jumped back to 0.

This is probably just another change that hides the underlying problem but i narrowed down the code change that affected us.  This prevents the change of page to 0 and therefore whatever is triggered that causes the error.  I have no idea if this change will break something else down the way so we will stay on v3.1.2 for now. In case it helps...

In 3.1.6 the line numbers are 315 and 316

```
_this.gridOptions.currentPage = 0;
 _this.scheduleDataFiltering();
```

I changed this in our v3.4 to the code from v3.2

```
var pageChanged = newValue[0] !== oldValue[0];
 if (!angular.equals(newValue, oldValue) && !pageChanged) {		
// everything will reset the page index, with the exception of a page index change
    if (_this.gridOptions.currentPage !== 0) {
         _this.gridOptions.currentPage = 0;	
         _this.scheduleDataFiltering();                            
           // the page index watch will activate, exit for now to avoid duplicate data requests		
          return;		
    }
  }
```
