### ISSUE TITLE
Trying to Include trNgGrid in my own transclude directive

### ISSUE THREAD

**Issue by Acruval** [MoonStorm/trNgGrid#177]
I tried to include trNgGrid in my own transclude directive. The  custom columns I defined are ignored.
http://plnkr.co/edit/GEGdJUE9O6SEJ0zLnl91?p=preview
Cheers

**Comment by MoonStorm** [comment]
Angular doesn't play nice with tables. Browsers don't play nice with table elements having invalid parents or children, even if they get in the right place later (you will actually experience DOM changes in these cases).

Here are three examples:
http://plnkr.co/edit/3h1DADy1FOoF1YBl6vYZ?p=preview

You can get some results by switching the driective from element to attribute, as in the third example, but even in this case, an additional element gets inserted into the ``table``, screwing the rendering. Due to that extra element, ``trnggrid`` also misses the template.

**Comment by Acruval** [comment]
Thanks for the explanation of the limits of angular with tables. You example was very interesting.
