### ISSUE TITLE
Underscore in field names

### ISSUE THREAD

**Issue by jmuilu** [MoonStorm/trNgGrid#179]
Looks like the field names are not shown properly if they contain underscores. E.g (in the plunker) FIRST_NAME is shown as FIRST

**Comment by MoonStorm** [comment]
You can provide a friendly name with the ``display-name`` attribute. 

What Plunker are you referring to?

**Comment by jmuilu** [comment]
Thanks for the response. I need to create columns dynamically and haven't found a solution which works for the case easily. Understood that some difficulties e.g. with  the ng-repeat tag.   Wondering if it would be possible to give the display names  as a list in the main element... 

I was referring to the plunker mentioned on the main github page (http://plnkr.co/edit/JCLrJD) 

Great thanks for the great component!!

**Comment by MoonStorm** [comment]
I hear what you're saying but I don't want to expose new features as workarounds just to get rid of them when ``ng-repeat`` would finally be available in this component. This just opens a can of worms and I'll be flooded with similar requests and will waste time implementing them instead of focusing on the right approach.

**Comment by jmuilu** [comment]
That make sense, good to keep the nice design. It was easy to make temporary fix so no probs with this.
