### ISSUE TITLE
Footer / paging

### ISSUE THREAD

**Issue by j-m-baker** [MoonStorm/trNgGrid#196]
How do I remove the footer with the paging option? I only want to see the grid...

Thanks

**Comment by MoonStorm** [comment]
Use some well targeted CSS.

**Comment by j-m-baker** [comment]
Will do - but think this would be a nice option for those who want to just display a table.

**Comment by MoonStorm** [comment]
There are a lot of variations it's virtually impossible to satisfy everyone's needs. Pager in the header, no footer, search at the top, different filtering, checkbox type selections, etc. 

Out of the box it's meant to satisfy the majority of use cases, otherwise it can be forked and tweaked for one's special requirements.
