### ISSUE TITLE
Feature request(s)

### ISSUE THREAD

**Issue by toddhd** [MoonStorm/trNgGrid#201]
Not sure if these exist, but I haven't seen them yet if so.

1) Option to hide the search field

The search textbox shows up on the bottom left corner, and there doesn't appear to be a native way to turn that off. It would be nice to add something like showSearchBar="false" to the HTML and have it not show up.

2) Page size drop-down

Would like to have a built-in page size dropdown (10,25,50,100) that would show up perhaps between the search textbox and the paging control, or on the left if the search textbox is not shown. Not entirely sure of how to implement it yet, but would nice if it could be customized (e.g. 5,10,15,20,25) easily.

**Comment by MoonStorm** [comment]
1) you can turn off global filtering and enable filtering on each individual column.
2) is a good idea and will come in a future release.
For now, just remember that all the [config options](http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions) are data-bindable.

[Here is a Plunker](http://plnkr.co/edit/Vi6Psz?p=preview) that would illustrate both points.

**Comment by Gorkfu** [comment]
There's an issue when changing the page size. The issue is that the "1-10 displayed" text doesn't get reported correctly on pages 2+ after changing the page size. For example lets say we have 60 items and on the initial page load you have it set to 5 items. It will display 1-5, then click page 2 it displays 6-10. It works how we expect; However, now when we use the dropdown to change the number of items to 10 per page. Page 1 displays 1-10, but page 2 displays 11-60 as the text, when it should display 11-20.

[See this plunker for the issue.](http://plnkr.co/edit/mZhLWF?p=preview)

After making the plunker I see that the page size jumps randomly. I was using sever side queries when I discovered this, so my pages would at least retain the correct number of items.
