### ISSUE TITLE
Delay filtering until user stops typing

### ISSUE THREAD

**Issue by vanpouckesven** [MoonStorm/trNgGrid#209]
Hello

I'm wondering if it's possible to delay the filtering of a column / table until the user stops typing. Currently we have a table with 1500 records that are loaded in memory. This is working great but when searching the grid reacts a bit slowly. I think that the perception would be better if the grid isn't searching after each letter but only when the user stops typing. 

Normally this kind of feature can be achieved by setting a timeout when the user enters and clears the timeout when the user is still typing after x milliseconds. 

I've been looking into the code if it was possible to change this behavior but i'm guessing since the filtering is happening client side, the filtering is automatically triggered due to the model bind of the columnOptions?

Could this be achieved easily or with an extension of the current code? 

Thanks in advance!

Sven

**Comment by MoonStorm** [comment]
Yes it can be achieved. It's the first time someone is asking for this feature, since loading a great number of rows in memory client-side is usually a bad idea. 

The mechanism you described is being used for server-side mode. Check the [demo site](http://moonstorm.github.io/trNgGrid/release/#/ServerSide) to see it in action.

My suggestion is to fork the project and implement this yourself. In client-side mode, there is a single function that gets called on model change that handles recomputing the items visible on the current page. As you already mentioned, you need to delay the call to this method on a timer and also cancel the timer when the same event occurred. 
You could use as inspiration the code for server-side mode, but that's slightly more complex since the call must be made instantly in case one of the order glyph is being clicked or a page transition is requested.

**Comment by vanpouckesven** [comment]
I finally found a solution for this problem so i wanted to share this with you guys. 

You can easily do this by overwriting the template for the trNgGridColumnFilter.html and trNgGridGlobalFilter.html by adding the following attribute to the input field for the search. 

ng-model-options="{ debounce: { 'default': 750, 'blur': 0 } }"
