### ISSUE TITLE
TrNgGrid Using Arabic Numerals in paging numbers 

### ISSUE THREAD

**Issue by Ahmed-Raouf** [MoonStorm/trNgGrid#215]
Hi All,

I need to display pager numbers in Arabic instead of English numerals. Anyone can help me?

Thanks

**Comment by MoonStorm** [comment]
A first thought would be changing the pager template and applying the localization filter on the numbers, same as it's been done for headers and any other label on the grid. Check the localization and the customization sections on the demo site. Let me know if this idea works for you. 

You might have to also tweak the localization filter as well, in order to cope with multiple digits. Can't really help much more, since I don't know anything about Arabic numerals.
